using Microsoft.EntityFrameworkCore.Migrations;

namespace Imersao_dados_csv_import.Migrations
{
    public partial class Create_Database : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "MicroDados",
                columns: table => new
                {
                    INSCRICAO = table.Column<string>(nullable: false),
                    ANO = table.Column<string>(nullable: true),
                    COD_MUNICIPIO_RESIDENCIA = table.Column<string>(nullable: true),
                    MUNICIPIO_RESIDENCIA = table.Column<string>(nullable: true),
                    COD_UF_RESIDENCIA = table.Column<string>(nullable: true),
                    UF_RESIDENCIA = table.Column<string>(nullable: true),
                    IDADE = table.Column<string>(nullable: true),
                    SEXO = table.Column<string>(nullable: true),
                    ESTADO_CIVIL = table.Column<string>(nullable: true),
                    COR_RACA = table.Column<string>(nullable: true),
                    NACIONALIDADE = table.Column<string>(nullable: true),
                    COD_MUNICIPIO_NASCIMENTO = table.Column<string>(nullable: true),
                    MUNICIPIO_NASCIMENTO = table.Column<string>(nullable: true),
                    COD_UF_NASCIMENTO = table.Column<string>(nullable: true),
                    UF_NASCIMENTO = table.Column<string>(nullable: true),
                    SITUACAO_CONCLUSAO = table.Column<string>(nullable: true),
                    ANO_CONCLUIU = table.Column<string>(nullable: true),
                    ESCOLA = table.Column<string>(nullable: true),
                    ENSINO = table.Column<string>(nullable: true),
                    TREINEIRO = table.Column<string>(nullable: true),
                    COD_ESCOLA = table.Column<string>(nullable: true),
                    COD_MUNICIPIO_ESC = table.Column<string>(nullable: true),
                    MUNICIPIO_ESC = table.Column<string>(nullable: true),
                    COD_UF_ESC = table.Column<string>(nullable: true),
                    UF_ESC = table.Column<string>(nullable: true),
                    DEPENDENCIA_ADM_ESCOLA = table.Column<string>(nullable: true),
                    LOCALIZACAO_ESCOLA = table.Column<string>(nullable: true),
                    SITUACAO_FUNC_ESCOLA = table.Column<string>(nullable: true),
                    IND_BAIXA_VISAO = table.Column<string>(nullable: true),
                    IND_CEGUEIRA = table.Column<string>(nullable: true),
                    IND_SURDEZ = table.Column<string>(nullable: true),
                    IND_DEFICIENCIA_AUDITIVA = table.Column<string>(nullable: true),
                    IND_SURDO_CEGUEIRA = table.Column<string>(nullable: true),
                    IND_DEFICIENCIA_FISICA = table.Column<string>(nullable: true),
                    IND_DEFICIENCIA_MENTAL = table.Column<string>(nullable: true),
                    IND_DEFICIT_ATENCAO = table.Column<string>(nullable: true),
                    IND_DISLEXIA = table.Column<string>(nullable: true),
                    IND_DISCALCULIA = table.Column<string>(nullable: true),
                    IND_AUTISMO = table.Column<string>(nullable: true),
                    IND_VISAO_MONOCULAR = table.Column<string>(nullable: true),
                    IND_OUTRA_DEF = table.Column<string>(nullable: true),
                    IND_GESTANTE = table.Column<string>(nullable: true),
                    IND_LACTANTE = table.Column<string>(nullable: true),
                    IND_IDOSO = table.Column<string>(nullable: true),
                    IND_ESTUDA_CLASSE_HOSPITALAR = table.Column<string>(nullable: true),
                    IND_SEM_RECURSO = table.Column<string>(nullable: true),
                    IND_BRAILLE = table.Column<string>(nullable: true),
                    IND_AMPLIADA_24 = table.Column<string>(nullable: true),
                    IND_AMPLIADA_18 = table.Column<string>(nullable: true),
                    IND_LEDOR = table.Column<string>(nullable: true),
                    IND_ACESSO = table.Column<string>(nullable: true),
                    IND_TRANSCRICAO = table.Column<string>(nullable: true),
                    IND_LIBRAS = table.Column<string>(nullable: true),
                    IND_TEMPO_ADICIONAL = table.Column<string>(nullable: true),
                    IND_LEITURA_LABIAL = table.Column<string>(nullable: true),
                    IND_MESA_CADEIRA_RODAS = table.Column<string>(nullable: true),
                    IND_MESA_CADEIRA_SEPARADA = table.Column<string>(nullable: true),
                    IND_APOIO_PERNA = table.Column<string>(nullable: true),
                    IND_GUIA_INTERPRETE = table.Column<string>(nullable: true),
                    IND_COMPUTADOR = table.Column<string>(nullable: true),
                    IND_CADEIRA_ESPECIAL = table.Column<string>(nullable: true),
                    IND_CADEIRA_CANHOTO = table.Column<string>(nullable: true),
                    IND_CADEIRA_ACOLCHOADA = table.Column<string>(nullable: true),
                    IND_PROVA_DEITADO = table.Column<string>(nullable: true),
                    IND_MOBILIARIO_OBESO = table.Column<string>(nullable: true),
                    IND_LAMINA_OVERLAY = table.Column<string>(nullable: true),
                    IND_PROTETOR_AURICULAR = table.Column<string>(nullable: true),
                    IND_MEDIDOR_GLICOSE = table.Column<string>(nullable: true),
                    IND_MAQUINA_BRAILE = table.Column<string>(nullable: true),
                    IND_SOROBAN = table.Column<string>(nullable: true),
                    IND_MARCA_PASSO = table.Column<string>(nullable: true),
                    IND_SONDA = table.Column<string>(nullable: true),
                    IND_MEDICAMENTOS = table.Column<string>(nullable: true),
                    IND_SALA_INDIVIDUAL = table.Column<string>(nullable: true),
                    IND_SALA_ESPECIAL = table.Column<string>(nullable: true),
                    IND_SALA_ACOMPANHANTE = table.Column<string>(nullable: true),
                    IND_MOBILIARIO_ESPECIFICO = table.Column<string>(nullable: true),
                    IND_MATERIAL_ESPECIFICO = table.Column<string>(nullable: true),
                    IND_NOME_SOCIAL = table.Column<string>(nullable: true),
                    COD_MUNICIPIO_PROVA = table.Column<string>(nullable: true),
                    MUNICIPIO_PROVA = table.Column<string>(nullable: true),
                    COD_UF_PROVA = table.Column<string>(nullable: true),
                    UF_PROVA = table.Column<string>(nullable: true),
                    PRESENCA_CN = table.Column<string>(nullable: true),
                    PRESENCA_CH = table.Column<string>(nullable: true),
                    PRESENCA_LC = table.Column<string>(nullable: true),
                    PRESENCA_MT = table.Column<string>(nullable: true),
                    COD_PROVA_CN = table.Column<string>(nullable: true),
                    COD_PROVA_CH = table.Column<string>(nullable: true),
                    COD_PROVA_LC = table.Column<string>(nullable: true),
                    COD_PROVA_MT = table.Column<string>(nullable: true),
                    NOTA_CN = table.Column<string>(nullable: true),
                    NOTA_CH = table.Column<string>(nullable: true),
                    NOTA_LC = table.Column<string>(nullable: true),
                    NOTA_MT = table.Column<string>(nullable: true),
                    TX_RESPOSTAS_CN = table.Column<string>(nullable: true),
                    TX_RESPOSTAS_CH = table.Column<string>(nullable: true),
                    TX_RESPOSTAS_LC = table.Column<string>(nullable: true),
                    TX_RESPOSTAS_MT = table.Column<string>(nullable: true),
                    TP_LINGUA = table.Column<string>(nullable: true),
                    TX_GABARITO_CN = table.Column<string>(nullable: true),
                    TX_GABARITO_CH = table.Column<string>(nullable: true),
                    TX_GABARITO_LC = table.Column<string>(nullable: true),
                    TX_GABARITO_MT = table.Column<string>(nullable: true),
                    TP_STATUS_REDACAO = table.Column<string>(nullable: true),
                    NU_NOTA_COMP1 = table.Column<string>(nullable: true),
                    NU_NOTA_COMP2 = table.Column<string>(nullable: true),
                    NU_NOTA_COMP3 = table.Column<string>(nullable: true),
                    NU_NOTA_COMP4 = table.Column<string>(nullable: true),
                    NU_NOTA_COMP5 = table.Column<string>(nullable: true),
                    NU_NOTA_REDACAO = table.Column<string>(nullable: true),
                    ESTUDO_PAI = table.Column<string>(nullable: true),
                    ESTUDO_MAE = table.Column<string>(nullable: true),
                    OCUPACAO_PAI = table.Column<string>(nullable: true),
                    OCUPACAO_MAE = table.Column<string>(nullable: true),
                    PESSOAS_RESIDENCIA = table.Column<string>(nullable: true),
                    RENDA_FAMILIAR = table.Column<string>(nullable: true),
                    EMPREGADO_DOMESTICO = table.Column<string>(nullable: true),
                    BANHEIRO = table.Column<string>(nullable: true),
                    QUARTOS = table.Column<string>(nullable: true),
                    CARRO = table.Column<string>(nullable: true),
                    MOTO = table.Column<string>(nullable: true),
                    GELADEIRA = table.Column<string>(nullable: true),
                    FREEZER = table.Column<string>(nullable: true),
                    MAQ_LAVAR = table.Column<string>(nullable: true),
                    SECA_ROUPA = table.Column<string>(nullable: true),
                    MICRO_ONDAS = table.Column<string>(nullable: true),
                    LAVAR_LOUCA = table.Column<string>(nullable: true),
                    ASPIRADOR_PO = table.Column<string>(nullable: true),
                    TV_CORES = table.Column<string>(nullable: true),
                    DVD = table.Column<string>(nullable: true),
                    TV_ASSINATURA = table.Column<string>(nullable: true),
                    CELULAR = table.Column<string>(nullable: true),
                    TEL_FIXO = table.Column<string>(nullable: true),
                    COMPUTADOR = table.Column<string>(nullable: true),
                    INTERNET = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_MicroDados", x => x.INSCRICAO);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "MicroDados");
        }
    }
}
