// <auto-generated />
using Imersao_dados_csv_import.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Imersao_dados_csv_import.Migrations
{
    [DbContext(typeof(MicroDadosContext))]
    partial class MicroDadosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Imersao_dados_csv_import.Models.MicroDado", b =>
                {
                    b.Property<string>("INSCRICAO")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("ANO")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ANO_CONCLUIU")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ASPIRADOR_PO")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("BANHEIRO")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CARRO")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CELULAR")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("COD_ESCOLA")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("COD_MUNICIPIO_ESC")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("COD_MUNICIPIO_NASCIMENTO")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("COD_MUNICIPIO_PROVA")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("COD_MUNICIPIO_RESIDENCIA")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("COD_PROVA_CH")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("COD_PROVA_CN")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("COD_PROVA_LC")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("COD_PROVA_MT")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("COD_UF_ESC")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("COD_UF_NASCIMENTO")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("COD_UF_PROVA")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("COD_UF_RESIDENCIA")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("COMPUTADOR")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("COR_RACA")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DEPENDENCIA_ADM_ESCOLA")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DVD")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("EMPREGADO_DOMESTICO")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ENSINO")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ESCOLA")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ESTADO_CIVIL")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ESTUDO_MAE")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ESTUDO_PAI")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FREEZER")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("GELADEIRA")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IDADE")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_ACESSO")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_AMPLIADA_18")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_AMPLIADA_24")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_APOIO_PERNA")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_AUTISMO")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_BAIXA_VISAO")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_BRAILLE")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_CADEIRA_ACOLCHOADA")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_CADEIRA_CANHOTO")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_CADEIRA_ESPECIAL")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_CEGUEIRA")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_COMPUTADOR")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_DEFICIENCIA_AUDITIVA")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_DEFICIENCIA_FISICA")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_DEFICIENCIA_MENTAL")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_DEFICIT_ATENCAO")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_DISCALCULIA")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_DISLEXIA")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_ESTUDA_CLASSE_HOSPITALAR")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_GESTANTE")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_GUIA_INTERPRETE")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_IDOSO")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_LACTANTE")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_LAMINA_OVERLAY")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_LEDOR")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_LEITURA_LABIAL")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_LIBRAS")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_MAQUINA_BRAILE")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_MARCA_PASSO")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_MATERIAL_ESPECIFICO")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_MEDICAMENTOS")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_MEDIDOR_GLICOSE")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_MESA_CADEIRA_RODAS")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_MESA_CADEIRA_SEPARADA")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_MOBILIARIO_ESPECIFICO")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_MOBILIARIO_OBESO")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_NOME_SOCIAL")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_OUTRA_DEF")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_PROTETOR_AURICULAR")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_PROVA_DEITADO")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_SALA_ACOMPANHANTE")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_SALA_ESPECIAL")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_SALA_INDIVIDUAL")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_SEM_RECURSO")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_SONDA")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_SOROBAN")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_SURDEZ")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_SURDO_CEGUEIRA")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_TEMPO_ADICIONAL")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_TRANSCRICAO")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IND_VISAO_MONOCULAR")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("INTERNET")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("LAVAR_LOUCA")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("LOCALIZACAO_ESCOLA")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("MAQ_LAVAR")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("MICRO_ONDAS")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("MOTO")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("MUNICIPIO_ESC")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("MUNICIPIO_NASCIMENTO")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("MUNICIPIO_PROVA")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("MUNICIPIO_RESIDENCIA")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NACIONALIDADE")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NOTA_CH")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NOTA_CN")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NOTA_LC")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NOTA_MT")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NU_NOTA_COMP1")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NU_NOTA_COMP2")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NU_NOTA_COMP3")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NU_NOTA_COMP4")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NU_NOTA_COMP5")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NU_NOTA_REDACAO")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("OCUPACAO_MAE")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("OCUPACAO_PAI")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PESSOAS_RESIDENCIA")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PRESENCA_CH")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PRESENCA_CN")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PRESENCA_LC")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PRESENCA_MT")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("QUARTOS")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("RENDA_FAMILIAR")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SECA_ROUPA")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SEXO")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SITUACAO_CONCLUSAO")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SITUACAO_FUNC_ESCOLA")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TEL_FIXO")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TP_LINGUA")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TP_STATUS_REDACAO")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TREINEIRO")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TV_ASSINATURA")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TV_CORES")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TX_GABARITO_CH")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TX_GABARITO_CN")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TX_GABARITO_LC")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TX_GABARITO_MT")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TX_RESPOSTAS_CH")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TX_RESPOSTAS_CN")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TX_RESPOSTAS_LC")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TX_RESPOSTAS_MT")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UF_ESC")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UF_NASCIMENTO")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UF_PROVA")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UF_RESIDENCIA")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("INSCRICAO");

                    b.ToTable("MicroDados");
                });
#pragma warning restore 612, 618
        }
    }
}
