using System.ComponentModel.DataAnnotations;

namespace Imersao_dados_csv_import.Models
{
    public class MicroDado
    {
        [Key]
        public string INSCRICAO { get; set; }
        public string ANO { get; set; }
        public string COD_MUNICIPIO_RESIDENCIA { get; set; }
        public string MUNICIPIO_RESIDENCIA { get; set; }
        public string COD_UF_RESIDENCIA { get; set; }
        public string UF_RESIDENCIA { get; set; }
        public string IDADE { get; set; }
        public string SEXO { get; set; }
        public string ESTADO_CIVIL { get; set; }
        public string COR_RACA { get; set; }
        public string NACIONALIDADE { get; set; }
        public string COD_MUNICIPIO_NASCIMENTO { get; set; }
        public string MUNICIPIO_NASCIMENTO { get; set; }
        public string COD_UF_NASCIMENTO { get; set; }
        public string UF_NASCIMENTO { get; set; }
        public string SITUACAO_CONCLUSAO { get; set; }
        public string ANO_CONCLUIU { get; set; }
        public string ESCOLA { get; set; }
        public string ENSINO { get; set; }
        public string TREINEIRO { get; set; }
        public string COD_ESCOLA { get; set; }
        public string COD_MUNICIPIO_ESC { get; set; }
        public string MUNICIPIO_ESC { get; set; }
        public string COD_UF_ESC { get; set; }
        public string UF_ESC { get; set; }
        public string DEPENDENCIA_ADM_ESCOLA { get; set; }
        public string LOCALIZACAO_ESCOLA { get; set; }
        public string SITUACAO_FUNC_ESCOLA { get; set; }
        public string IND_BAIXA_VISAO { get; set; }
        public string IND_CEGUEIRA { get; set; }
        public string IND_SURDEZ { get; set; }
        public string IND_DEFICIENCIA_AUDITIVA { get; set; }
        public string IND_SURDO_CEGUEIRA { get; set; }
        public string IND_DEFICIENCIA_FISICA { get; set; }
        public string IND_DEFICIENCIA_MENTAL { get; set; }
        public string IND_DEFICIT_ATENCAO { get; set; }
        public string IND_DISLEXIA { get; set; }
        public string IND_DISCALCULIA { get; set; }
        public string IND_AUTISMO { get; set; }
        public string IND_VISAO_MONOCULAR { get; set; }
        public string IND_OUTRA_DEF { get; set; }
        public string IND_GESTANTE { get; set; }
        public string IND_LACTANTE { get; set; }
        public string IND_IDOSO { get; set; }
        public string IND_ESTUDA_CLASSE_HOSPITALAR { get; set; }
        public string IND_SEM_RECURSO { get; set; }
        public string IND_BRAILLE { get; set; }
        public string IND_AMPLIADA_24 { get; set; }
        public string IND_AMPLIADA_18 { get; set; }
        public string IND_LEDOR { get; set; }
        public string IND_ACESSO { get; set; }
        public string IND_TRANSCRICAO { get; set; }
        public string IND_LIBRAS { get; set; }
        public string IND_TEMPO_ADICIONAL { get; set; }
        public string IND_LEITURA_LABIAL { get; set; }
        public string IND_MESA_CADEIRA_RODAS { get; set; }
        public string IND_MESA_CADEIRA_SEPARADA { get; set; }
        public string IND_APOIO_PERNA { get; set; }
        public string IND_GUIA_INTERPRETE { get; set; }
        public string IND_COMPUTADOR { get; set; }
        public string IND_CADEIRA_ESPECIAL { get; set; }
        public string IND_CADEIRA_CANHOTO { get; set; }
        public string IND_CADEIRA_ACOLCHOADA { get; set; }
        public string IND_PROVA_DEITADO { get; set; }
        public string IND_MOBILIARIO_OBESO { get; set; }
        public string IND_LAMINA_OVERLAY { get; set; }
        public string IND_PROTETOR_AURICULAR { get; set; }
        public string IND_MEDIDOR_GLICOSE { get; set; }
        public string IND_MAQUINA_BRAILE { get; set; }
        public string IND_SOROBAN { get; set; }
        public string IND_MARCA_PASSO { get; set; }
        public string IND_SONDA { get; set; }
        public string IND_MEDICAMENTOS { get; set; }
        public string IND_SALA_INDIVIDUAL { get; set; }
        public string IND_SALA_ESPECIAL { get; set; }
        public string IND_SALA_ACOMPANHANTE { get; set; }
        public string IND_MOBILIARIO_ESPECIFICO { get; set; }
        public string IND_MATERIAL_ESPECIFICO { get; set; }
        public string IND_NOME_SOCIAL { get; set; }
        public string COD_MUNICIPIO_PROVA { get; set; }
        public string MUNICIPIO_PROVA { get; set; }
        public string COD_UF_PROVA { get; set; }
        public string UF_PROVA { get; set; }
        public string PRESENCA_CN { get; set; }
        public string PRESENCA_CH { get; set; }
        public string PRESENCA_LC { get; set; }
        public string PRESENCA_MT { get; set; }
        public string COD_PROVA_CN { get; set; }
        public string COD_PROVA_CH { get; set; }
        public string COD_PROVA_LC { get; set; }
        public string COD_PROVA_MT { get; set; }
        public string NOTA_CN { get; set; }
        public string NOTA_CH { get; set; }
        public string NOTA_LC { get; set; }
        public string NOTA_MT { get; set; }
        public string TX_RESPOSTAS_CN { get; set; }
        public string TX_RESPOSTAS_CH { get; set; }
        public string TX_RESPOSTAS_LC { get; set; }
        public string TX_RESPOSTAS_MT { get; set; }
        public string TP_LINGUA { get; set; }
        public string TX_GABARITO_CN { get; set; }
        public string TX_GABARITO_CH { get; set; }
        public string TX_GABARITO_LC { get; set; }
        public string TX_GABARITO_MT { get; set; }
        public string TP_STATUS_REDACAO { get; set; }
        public string NU_NOTA_COMP1 { get; set; }
        public string NU_NOTA_COMP2 { get; set; }
        public string NU_NOTA_COMP3 { get; set; }
        public string NU_NOTA_COMP4 { get; set; }
        public string NU_NOTA_COMP5 { get; set; }
        public string NU_NOTA_REDACAO { get; set; }
        public string ESTUDO_PAI { get; set; }
        public string ESTUDO_MAE { get; set; }
        public string OCUPACAO_PAI { get; set; }
        public string OCUPACAO_MAE { get; set; }
        public string PESSOAS_RESIDENCIA { get; set; }
        public string RENDA_FAMILIAR { get; set; }
        public string EMPREGADO_DOMESTICO { get; set; }
        public string BANHEIRO { get; set; }
        public string QUARTOS { get; set; }
        public string CARRO { get; set; }
        public string MOTO { get; set; }
        public string GELADEIRA { get; set; }
        public string FREEZER { get; set; }
        public string MAQ_LAVAR { get; set; }
        public string SECA_ROUPA { get; set; }
        public string MICRO_ONDAS { get; set; }
        public string LAVAR_LOUCA { get; set; }
        public string ASPIRADOR_PO { get; set; }
        public string TV_CORES { get; set; }
        public string DVD { get; set; }
        public string TV_ASSINATURA { get; set; }
        public string CELULAR { get; set; }
        public string TEL_FIXO { get; set; }
        public string COMPUTADOR { get; set; }
        public string INTERNET { get; set; }
    }
}
